server:
  port: 8069
  servlet:
    context-path: /doctor
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-store: classpath:ssl-server.jks
    key-store-type: JKS
    key-password: changeit

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:mysql://localhost:3306/doctordetails?createDatabaseIfNotExist=true
    username: root
    password: 465765
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MySQL8Dialect

swagger:
  url:
    localURL: https://localhost:${server.port}/doctor

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  file:
    name: doctor.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    "[org.springframework.web]": INFO
    "[com.doctorservice]": DEBUG
    "[org.hibernate]": INFO
